# Generated by Django 5.2.7 on 2025-10-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
